// Slint default template
// https://github.com/slint-ui/slint-rust-template/archive/refs/heads/main.zip

import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 0;
    callback request-increase-value();
    callback request-decrease-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
        Button {
            text: "Decrease value";
            clicked => {
                root.request-decrease-value();
            }
        }
    }
}
