[workspace]

resolver = "2"
members = [
  "counter",
  "temp-converter",
  "flight-booker",
  "timer",
  "crud",
  "circle-drawer",
  "cells"
]

[workspace.dependencies]
slint = "1.8.0"
slint-build = "1.8.0"
