[workspace]

resolver = "2"
members = [
  "counter",
  "temp-converter",
  "flight-booker",
  "timer",
  "crud",
  "circle-drawer",
  "cells"
]

[workspace.dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
