[workspace]

resolver = "2"
members = [
   "iced-sv",
   "slint-sv",
   "gpui-sv",
   "floem-sv",
   "xilem-sv",
   "freya-sv",
]

[workspace.dependencies]
time = {version = "0.3.36", features = ["std", "macros", "formatting", "parsing"]}
tokio = "1.46.1"
undo_2 = "0.2.1"
